import { StringTable } from "../../src/ui/presentation/presentation";

export const koEnglishStrings: StringTable = {
    "entity.ko.name": "Ko-chan",
    "entity.ko.desc": "Student council president.  Self-proclaimed fairy.",

    "passive.thousandRestraintsBody.name": "Thousand Restraints Body",
    "passive.thousandRestraintsBody.desc": "Use limb-based moves despite binding restrictions, but lose the ability to Escape.",

    "move.telekinesis.name": "Telekinesis",
    "move.telekinesis.desc": "Strike an enemy with telekinetic force.",
    "move.fairyTelekinesis.name": "Fairy Telekinesis",
    "move.fairyTelekinesis.desc": "An empowered telekinetic attack against every enemy.",
    "move.starlightBindings.name": "Starlight Bindings",
    "move.starlightBindings.desc": "Restrain an enemy with starlight, reducing defense and accuracy.",
    "move.fairyStarlightBindings.name": "Fairy Starlight Bindings",
    "move.fairyStarlightBindings.desc": "Spread starlight restraints across all enemies.",
    "move.reflect.name": "Reflect",
    "move.reflect.desc": "Reflect the next enemy binding application.",
    "move.fairyReflect.name": "Fairy Reflect",
    "move.fairyReflect.desc": "An empowered reflection that prevents the incoming binding.",
    "move.fairyTransformation.name": "Fairy Transformation",
    "move.fairyTransformation.desc": "Transform and unlock empowered magic.",
    "move.fairyEmpowerment.name": "Fairy Empowerment",
    "move.fairyEmpowerment.desc": "Share defensive magic and empowerment with the party.",
    "move.powerOfDenial.name": "[Power of Denial]",
    "move.powerOfDenial.desc": "Deny a binding or defeat a non-boss enemy once per encounter.",

    "buff.transformation.name": "Fairy Transformation",
    "buff.transformation.desc": "...",
    "buff.empowerment.name": "Fairy Empowerment",
    "buff.empowerment.desc": "...",
    "buff.empowerment.allow": "Adds Empowered Moves",
    "buff.reflect.name": "Reflect",
    "buff.reflect.desc": "...",
    "buff.fairyReflect.name": "Fairy Reflect",
    "buff.fairyReflect.desc": "...",
    "buff.starlightBindings.name": "Starlight Bindings",
    "buff.starlightBindings.desc": "...",
    "buff.exhausted.name": "Exhausted",
    "buff.exhausted.desc": "...",
    "buff.exhausted.block": "Seals [Power of Denial]",
};

export const matsukoEnglishStrings: StringTable = {
    "entity.matsuko.name": "Matsuko",
    "entity.matsuko.desc": "Student council vice-president.  Young Mistress of the Flame Clan.",

    "move.punch.name": "Punch",
    "move.punch.desc": "A basic punch.",
    "move.kick.name": "Kick",
    "move.kick.desc": "A basic kick.",
    "move.whiteFlame.name": "White Flame",
    "move.whiteFlame.desc": "An accurate flame attack.",
    "move.fairyWhiteFlame.name": "Fairy White Flame",
    "move.fairyWhiteFlame.desc": "An empowered flame attack against all enemies.",
    "move.phoenixKick.name": "Phoenix Kick",
    "move.phoenixKick.desc": "A potent flame kick.",
    "move.fairyPhoenixKick.name": "Fairy Phoenix Kick",
    "move.fairyPhoenixKick.desc": "An empowered double flame kick.",
    "move.immolation.name": "Immolation",
    "move.immolation.desc": "Burn away restraints in an all-enemy attack, at the cost of flame powers.",
    "move.obey.name": "[Compulsion: Obey]",
    "move.obey.desc": "Compel an ally to act again, temporarily sealing their Escape.",
    "move.stop.name": "[Compulsion: Stop]",
    "move.stop.desc": "Interrupt or weaken an enemy’s planned actions.",
    "move.attackMe.name": "[Compulsion: Taunt]",
    "move.attackMe.desc": "Draw enemy attacks toward the caster while raising defense.",

    "buff.burnout.name": "Burnout",
    "buff.burnout.desc": "...",
    "buff.burnout.block": "Seals Flame Moves",
    "buff.burnout.allow": "Adds Basic Moves",
    "buff.defenseBarrier.name": "Defense Barrier",
    "buff.defenseBarrier.desc": "...",
    "buff.servitude.name": "Servitude",
    "buff.servitude.desc": "...",
};

export const hinariEnglishStrings: StringTable = {
    "entity.hinari.name": "Hinari",
    "entity.hinari.desc": "Student council treasurer.  Adept of the Power of Space.",

    "passive.subspaceMovement.name": "Subspace Movement",
    "passive.subspaceMovement.desc": "Ignore traps and resist leg-restricting statuses.",
    "move.rockfall.name": "Rockfall",
    "move.rockfall.desc": "Strike an enemy with multiple falling rocks.",
    "move.fairyRockfall.name": "Fairy Rockfall",
    "move.fairyRockfall.desc": "An empowered barrage of falling rocks.",
    "move.store.name": "Store",
    "move.store.desc": "Store material from a character’s strongest binding in Subspace.",
    "move.brace.name": "Brace",
    "move.brace.desc": "Prepare to absorb an enemy binding into Subspace.",
    "move.release.name": "Release",
    "move.release.desc": "Release stored material as a binding or an enemy debuff.",

    "buff.brace.name": "Brace",
    "buff.brace.desc": "...",
    "buff.subspaceClutter.name": "Subspace Clutter",
    "buff.subspaceClutter.desc": "...",

    "data.subspace.name": "Subspace",
    "data.subspace.short": "Sub",
};