import { StringTable } from "../../src/ui/presentation/presentation";

export const koEnglishStrings: StringTable = {
    "entity.ko.name": "Ko-chan",
    "entity.ko.desc": "Student council president.  Self-proclaimed fairy.",

    "passive.thousandRestraintsBody.name": "Thousand Restraints Body",
    "passive.thousandRestraintsBody.desc": "...",

    "move.telekinesis.name": "Telekinesis",
    "move.telekinesis.desc": "...",
    "move.fairyTelekinesis.name": "Fairy Telekinesis",
    "move.fairyTelekinesis.desc": "...",
    "move.starlightBindings.name": "Starlight Bindings",
    "move.starlightBindings.desc": "...",
    "move.fairyStarlightBindings.name": "Fairy Starlight Bindings",
    "move.fairyStarlightBindings.desc": "...",
    "move.reflect.name": "Reflect",
    "move.reflect.desc": "...",
    "move.fairyReflect.name": "Fairy Reflect",
    "move.fairyReflect.desc": "...",
    "move.fairyTransformation.name": "Fairy Transformation",
    "move.fairyTransformation.desc": "...",
    "move.fairyEmpowerment.name": "Fairy Empowerment",
    "move.fairyEmpowerment.desc": "...",
    "move.powerOfDenial.name": "[Power of Denial]",
    "move.powerOfDenial.desc": "...",

    "buff.transformation.name": "Fairy Transformation",
    "buff.transformation.desc": "...",
    "buff.empowerment.name": "Fairy Empowerment",
    "buff.empowerment.desc": "...",
    "buff.reflect.name": "Reflect",
    "buff.reflect.desc": "...",
    "buff.fairyReflect.name": "Fairy Reflect",
    "buff.fairyReflect.desc": "...",
    "buff.starlightBindings.name": "Starlight Bindings",
    "buff.starlightBindings.desc": "...",
    "buff.exhausted.name": "Exhausted",
    "buff.exhausted.desc": "...",

    // Matsuko
    "move.punch.name": "Punch",
    "move.punch.desc": "...",
    "move.kick.name": "Kick",
    "move.kick.desc": "...",
    "move.whiteFlame.name": "White Flame",
    "move.whiteFlame.desc": "...",
    "move.fairyWhiteFlame.name": "Fairy White Flame",
    "move.fairyWhiteFlame.desc": "...",
    "move.phoenixKick.name": "Phoenix Kick",
    "move.phoenixKick.desc": "...",
    "move.fairyPhoenixKick.name": "Fairy Phoenix Kick",
    "move.fairyPhoenixKick.desc": "...",
    "move.immolation.name": "Immolation",
    "move.immolation.desc": "...",
    "move.obey.name": "[Power of Compulsion: Obey]",
    "move.obey.desc": "...",
    "move.stop.name": "[Power of Compulsion: Stop]",
    "move.stop.desc": "...",
    "move.attackMe.name": "[Power of Compulsion: Taunt]",
    "move.attackMe.desc": "...",

    "buff.burnout.name": "Burnout",
    "buff.burnout.desc": "...",
    "buff.defenseBarrier.name": "Defense Barrier",
    "buff.defenseBarrier.desc": "...",
    "buff.servitude.name": "Servitude",
    "buff.servitude.desc": "...",
};

export const matsukoEnglishStrings: StringTable = {
    "entity.matsuko.name": "Matsuko",
    "entity.matsuko.desc": "Student council vice-president.  Young Mistress of the Flame Clan.",

    "move.punch.name": "Punch",
    "move.punch.desc": "...",
    "move.kick.name": "Kick",
    "move.kick.desc": "...",
    "move.whiteFlame.name": "White Flame",
    "move.whiteFlame.desc": "...",
    "move.fairyWhiteFlame.name": "Fairy White Flame",
    "move.fairyWhiteFlame.desc": "...",
    "move.phoenixKick.name": "Phoenix Kick",
    "move.phoenixKick.desc": "...",
    "move.fairyPhoenixKick.name": "Fairy Phoenix Kick",
    "move.fairyPhoenixKick.desc": "...",
    "move.immolation.name": "Immolation",
    "move.immolation.desc": "...",
    "move.obey.name": "[Power of Compulsion: Obey]",
    "move.obey.desc": "...",
    "move.stop.name": "[Power of Compulsion: Stop]",
    "move.stop.desc": "...",
    "move.attackMe.name": "[Power of Compulsion: Taunt]",
    "move.attackMe.desc": "...",

    "buff.burnout.name": "Burnout",
    "buff.burnout.desc": "...",
    "buff.defenseBarrier.name": "Defense Barrier",
    "buff.defenseBarrier.desc": "...",
    "buff.servitude.name": "Servitude",
    "buff.servitude.desc": "...",
};

export const hinariEnglishStrings: StringTable = {
    "entity.hinari.name": "Hinari",
    "entity.hinari.desc": "Student council treasurer.  Adept of the Power of Space.",

    "passive.subspaceMovement.name": "Subspace Movement",
    "passive.subspaceMovement.desc": "...",
    "move.rockfall.name": "Rockfall",
    "move.rockfall.desc": "...",
    "move.fairyRockfall.name": "Fairy Rockfall",
    "move.fairyRockfall.desc": "...",
    "move.store.name": "Store",
    "move.store.desc": "...",
    "move.brace.name": "Brace",
    "move.brace.desc": "...",
    "move.release.name": "Release",
    "move.release.desc": "...",

    "buff.brace.name": "Brace",
    "buff.brace.desc": "...",
    "buff.subspaceClutter.name": "Subspace Clutter",
    "buff.subspaceClutter.desc": "...",

    "data.subspace.name": "Subspace",
    "data.subspace.short": "Sub",
};