import type { StringTable } from "../../src/ui/presentation/presentation";

/** Bracketed category:id tokens become campaign-scoped reference links in the Library. */
export const libraryEnglishStrings: StringTable = {
    "ui.library.grantedBy": "Granted By",
    "move.throwOff.source": "[enemies:skunkette]",
    "ui.library.baseMoves": "Base Moves",
    "ui.library.effects": "Effects",
    "ui.library.strategy": "Strategy",
    "ui.library.difficultyModifiers": "Difficulty Modifiers",
    "ui.library.target": "Target",
    "ui.library.duration": "Duration",
    "ui.library.modifiersAndRestrictions": "Modifiers & restrictions",
    "ui.library.triggerEffects": "Trigger Effects (when triggered)",
    "ui.library.triggerProbability": "Trigger Probability",
    "ui.library.outcomeProbability": "These chances are conditional on triggering at neutral Trap Avoidance and trap strength of 100 or less. Stronger traps and Trap Avoidance alter the distribution. Each binding application is capped by remaining strength.",
    "ui.library.probability": "{value}%",
    "ui.library.upTo": "Up to {amount}",
    "entity.skunkette.strategy": "If linked to a Pounce victim, uses [moves:latexSpray] on that victim.\nOtherwise, if [moves:pounce] is off cooldown, chooses a random valid character who is not already pounced.\nOtherwise, chooses [moves:latexMist] or [moves:latexSpray] with equal probability. Spray chooses a random valid character and a body-zone binding; falls back to Mist if no Spray target is available.",
    "entity.skunkette.rules": "Below 40% HP, gains Potency −4 and Defense −1.\nEach damaging application lowers [moves:pounce] severity by one; defeating the attacker removes Pounce.\nDefeating a Skunkette linked to a fully transformed character rescues that character and halves their bindings.",
    "entity.skunk.strategy": "Below 20% HP, uses [moves:latexExplosion] on the valid character with the highest total binding, or a random valid character if none is bound.\nOtherwise, may use [moves:latexPuddle]. The chance decreases as puddle strength rises: its roll must exceed current puddle strength + 25.\nOtherwise, may use [moves:latexRegeneration] on the character with the most binding removed below recorded peaks. Its roll must be lower than that total, then it chooses a random restorable binding.\nOtherwise, uses [moves:latexShower] on a random valid character and body zone, falling back to [moves:latexPuddle] if no attack target is available.",
    "entity.skunk.rules": "Crossing from at least 20% to below 20% HP while still alive cancels its intentions and immediately activates [moves:latexExplosion] against the attacker.",
    "entity.fairy.strategy": "Builds a list of eligible support actions: [moves:healingMagic] for damaged Skunkettes or Skunks; [moves:barrierMagic] for Skunkettes, Skunks, or Queens without a barrier; [moves:empoweringMagic] for Skunkettes, Skunks, or Queens.\nChooses uniformly among those eligible action types, then picks a random eligible target for that action.\nIf no support action is available, uses [moves:bindingMagic] on a random valid character and body zone.",
    "entity.rainmaker.strategy": "Uses [moves:latexRain] every turn, affecting the party.",
    "entity.queen.strategy": "If [moves:skunkCollar] is off cooldown and no valid character already has a collar, targets the character who has dealt the most damage to her. Chooses a random valid character if no damage has been recorded.\nOtherwise, if [moves:skunkPerfume] is off cooldown, chooses equally between its two debuffs; healing becomes a third equally likely option when a Skunkette, Skunk, or Fairy is damaged.\nOtherwise, uses [moves:skunkGun] on a random valid character and body zone. Falls back to Perfume when no valid gun target exists.",
    "entity.queen.rules": "Crossing 80%, 60%, 40%, and 20% HP activates [moves:callReinforcements] immediately.\nCrossing two-thirds and one-third HP activates [moves:latexRainmaker] immediately.\nEach threshold activates only the first time it is crossed. Encounter setup determines the next wave.",
    "binding.latexArms.light": "Simple latex gloves reach up to your elbows.",
    "binding.latexArms.moderate": "Thick latex gloves make it hard to manipulate things, and grow up to your shoulders.",
    "binding.latexArms.heavy": "Thick latex paw-shaped gloves cover your hands, making it nearly impossible to use them normally.",
    "binding.latexArms.severe": "Latex gloves fold over into half-length skunk paws, trapping your hands and arms against your shoulders.",
    "binding.latexArms.overwhelming": "Solid latex paws hold your hands and arms against your shoulders, leaving no room to move.",
    "binding.latexHead.light": "A light latex covering begins to surround your head.",
    "binding.latexHead.moderate": "The latex thickens around your mouth, making speech and mouth moves harder.",
    "binding.latexHead.heavy": "A thick latex hood presses around your head and mouth.",
    "binding.latexHead.severe": "The latex seals your mouth and encloses your head in a skunk-shaped hood.",
    "binding.latexHead.overwhelming": "A solid skunk hood holds your head and mouth tightly in place.",
    "binding.latexTorso.light": "A thin layer of living latex wraps around your torso.",
    "binding.latexTorso.moderate": "The latex thickens into a close-fitting suit around your torso.",
    "binding.latexTorso.heavy": "The suit tightens and begins to vibrate.",
    "binding.latexTorso.severe": "Dense vibrating latex constricts your torso.",
    "binding.latexTorso.overwhelming": "A solid vibrating suit encases your torso.",
    "binding.latexLegs.light": "Light latex stockings cover your legs.",
    "binding.latexLegs.moderate": "Thick latex stockings restrict your steps.",
    "binding.latexLegs.heavy": "The latex forms heavy skunk paws around your feet.",
    "binding.latexLegs.severe": "Dense latex holds your legs tightly together.",
    "binding.latexLegs.overwhelming": "Solid latex paws lock your legs in place.",
    "binding.latexCollar.light": "A living latex collar settles around your neck.",
    "binding.latexCollar.moderate": "The collar thickens, feeding latex onto your body.",
    "binding.latexCollar.heavy": "A heavy collar steadily supplies more living latex.",
    "binding.latexCollar.severe": "The dense collar presses firmly around your neck.",
    "binding.latexCollar.overwhelming": "A solid collar anchors the living latex around your neck.",
    "ui.library.title": "Library",
    "ui.library.intro": "Explore the characters, abilities, and mechanics in this campaign.",
    "ui.library.difficulties": "Difficulties",
    "ui.library.characters": "Characters",
    "ui.library.enemies": "Enemies",
    "ui.library.moves": "Moves",
    "ui.library.passives": "Passives",
    "ui.library.bindings": "Bindings",
    "ui.library.traps": "Traps",
    "ui.library.statuses": "Statuses",
    "ui.library.encounters": "Encounters",
    "ui.library.back": "Go Back",
    "ui.library.close": "Close Library",
    "ui.library.search": "Find an entry",
    "ui.library.count": "{count} entries",
    "ui.library.empty": "No entries in this category.",
    "ui.library.noResults": "No matching entries.",
    "ui.library.unavailable": "This entry is unavailable in this campaign.",
    "ui.library.attributes": "Base Attributes",
    "ui.library.mechanics": "Mechanics",
    "ui.library.related": "Related Entries",
    "ui.library.empoweredMoves": "Empowered Moves",
    "ui.library.startingResources": "Starting Resources",
    "ui.library.noResources": "No starting resources.",
    "ui.library.noPassives": "No innate passives.",
    "ui.library.noModifiers": "No modifiers.",
    "ui.library.noRestrictions": "No special restrictions.",
    "ui.library.noStatus": "No status at this threshold.",
    "ui.library.noMechanics": "No additional reference notes.",
    "ui.library.baseDamage": "Base Damage",
    "ui.library.baseAmount": "Base Effect Amount",
    "ui.library.baseNote": "Baseline per hit or effect, before combat modifiers, hit outcomes, and defense. Actual combat values may differ.",
    "ui.library.hits": "Hits",
    "ui.library.targeting": "Targeting",
    "ui.library.targetSide": "Target Side",
    "ui.library.targets": "Target Count",
    "ui.library.type": "Move Type",
    "ui.library.accuracy": "Base Accuracy",
    "ui.library.check": "Check",
    "ui.library.cooldowns": "Cooldowns Applied",
    "ui.library.cooldown": "{count} rounds",
    "ui.library.freeOnHit": "Does not consume the action on a successful hit.",
    "ui.library.alwaysAvailable": "Always available in the move list.",
    "ui.library.restrictions": "Restrictions",
    "ui.library.allowed": "Ignores Block {type}",
    "ui.library.blocked": "Blocks {type} moves",
    "ui.library.immunities": "Status Immunities",
    "ui.library.intensity": "Intensity {level}",
    "ui.library.intensityNote": "Each row shows the full effects at that intensity, not extra effects to add to earlier rows. The highest intensity of each status applies; duplicate sources do not stack.",
    "ui.library.progression": "Severity Progression",
    "ui.library.progressionNote": "Each threshold replaces the previous threshold’s status list. Status intensity is separate from binding severity.",
    "ui.library.range": "{min}–{max}",
    "ui.library.belowThreshold": "Below {min}, the binding has no severity. The first tier begins at {min}.",
    "ui.library.growthNote": "Binding added beyond the Overwhelming threshold is reduced to 10% of the overflowing amount, up to the maximum binding cap.",
    "ui.library.maximum": "Maximum binding: {max}.",
    "ui.library.rank": "Rank",
    "ui.library.hp": "Base HP",
    "ui.library.defense": "Base Defense",
    "ui.library.playerModifiers": "Player Modifiers",
    "ui.library.enemyModifiers": "Enemy Modifiers",
    "ui.library.specialRules": "Special Rules",
    "ui.library.setup": "Starting Effects",
    "ui.library.challenge": "Challenge",
    "ui.library.usedBy": "Used By",
    "ui.library.resource": "{name}: {value}",
    "ui.library.resourceRange": "{name}: {value} / {max}",
    "ui.library.severityName": "{difficulty} · {severity}",
    "ui.library.none": "None",
    "ui.library.all": "All",
    "ui.library.self": "Self / no selected target",
    "ui.library.either": "Players or enemies",
    "ui.library.player": "Players",
    "ui.library.enemy": "Enemies",
    "ui.library.untargeted": "No selected target",
    "ui.library.willpower": "Willpower",
    "ui.library.accuracyCheck": "Accuracy",
    "ui.library.light": "Easy",
    "ui.library.moderate": "Medium",
    "ui.library.heavy": "Hard",
    "ui.library.severe": "Extreme",
    "ui.library.overwhelming": "Impossible",
    "ui.library.noCheck": "No accuracy roll",
    "entity.ko.library": "Uses [moves:fairyTransformation] to unlock empowered moves. Each empowered move consumes empowerment.",
    "entity.matsuko.library": "Compulsion moves share cooldowns and do not consume Matsuko's action.",
    "entity.hinari.library": "Starts empty and has a max of 100.\n[moves:rockfall] deals more hits the lower Subspace is.\n[moves:store] and [moves:brace] fill Subspace; [moves:release] empties it.",
    "move.starlightBindings.library": "",
    "move.reflect.library": "",
    "move.fairyReflect.library": "",
    "move.fairyTransformation.library": "",
    "move.fairyTransformation.effect.empowerment.note": "Adds empowerment only when it is not already present.",
    "move.fairyEmpowerment.library": "",
    "move.fairyEmpowerment.effect.empowerment.note": "Each ally gains only their own empowered moves.",
    "move.powerOfDenial.library": "",
    "move.punch.library": "Added by [moves:immolation] after burnout.",
    "move.kick.library": "Added by [moves:immolation] after burnout.",
    "move.immolation.library": "",
    "move.obey.library": "Requires an ally who has already acted and is not affected by Servitude.",
    "move.stop.library": "",
    "move.attackMe.library": "",
    "move.rockfall.library": "The hit count falls as Subspace fills; full Subspace prevents use.\nDoes not spend Subspace. Use [moves:release] to make room for more hits.",
    "move.fairyRockfall.library": "The hit count falls as Subspace fills; full Subspace prevents use.\nDoes not spend Subspace.",
    "move.store.library": "Requires Subspace below 100 and an ally with at least one binding.",
    "move.brace.library": "Requires Subspace below 100.",
    "move.release.library": "Requires at least 25 Subspace and a remembered binding type.",
    "move.skunkCollar.library": "",
    "move.pounce.library": "Requires a target who is not already pounced. Higher hit effectiveness creates stronger Pounce severity. Damaging the attacker lowers severity by one; defeating it removes Pounce.",
    "move.throwOff.library": "Available to a victim of [moves:pounce].",
    "move.latexMist.library": "",
    "move.latexPuddle.library": "",
    "move.latexRegeneration.library": "",
    "move.latexExplosion.library": "",
    "move.healingMagic.library": "",
    "move.empoweringMagic.library": "",
    "move.barrierMagic.library": "",
    "move.latexRain.library": "",
    "move.callReinforcements.library": "Activates when the boss crosses 80%, 60%, 40%, and 20% HP for the first time. Encounter setup determines the next wave.",
    "move.latexRainmaker.library": "Activates when the boss crosses two-thirds and one-third HP for the first time. Encounter setup determines the construction wave.",
    "move.skunkPerfume.library": "Uses one of the three alternatives below. The healing option is available when an eligible enemy ally is damaged.",
    "entity.skunkette.library": "Prioritizes spraying a linked Pounce victim, otherwise attempts [moves:pounce] when available and alternates [moves:latexMist] and [moves:latexSpray].\nBelow 40% HP, victim resistance gives Potency −4 and Defense −1.\nDefeating the Skunkette linked to a fully skunked character rescues them and reduces their bindings by half.",
    "entity.skunk.library": "Creates [traps:trapPuddle] and uses [moves:latexRegeneration] to undo escape progress.\nCrossing below 20% HP while still alive interrupts its current intentions and immediately triggers [moves:latexExplosion] against the attacker.",
    "entity.fairy.library": "Supports allies with [moves:healingMagic], [moves:barrierMagic], and [moves:empoweringMagic]; uses [moves:bindingMagic] when no support action is available.",
    "entity.rainmaker.library": "Uses [moves:latexRain] every turn.\nDefeat adds 50 [traps:trapPuddle] on [difficulties:extreme], or 100 on [difficulties:mythic].",
    "entity.queen.library": "Uses [moves:skunkCollar] when no player has a collar, prioritizing the player who has dealt the most damage to her.\nUses [moves:skunkPerfume] when available; otherwise attacks with [moves:skunkGun].\nCrossing HP thresholds triggers [moves:callReinforcements] and [moves:latexRainmaker]. Those triggers only occur the first time each threshold is crossed.",
    "ui.library.blocksEscape": "Blocks Escape",
    "ui.library.cooldownHeading": "Cooldown",
    "ui.library.sharedCooldowns": "Also puts these moves on cooldown",
    "ui.library.freeAction": "Does not consume the action.",
    "ui.library.perHit": "Damage per hit",
    "ui.library.specialResource": "Special Resource: {name}",
    "ui.library.allowedExplanation": "Can use {type} moves even when a status blocks them. Accuracy penalties still apply.",
    "ui.library.blockedExplanation": "Cannot use {type} moves.",
    "ui.library.modifierExplanation": "Changes {modifier} by {value}.",
    "ui.library.immune": "Immune to {status}",
    "ui.library.immunityExplanation": "Unaffected by {status}, at any intensity.",
    "ui.library.statusColumn": "Status",
    "passive.thousandRestraintsBody.summary": "Keeps Mouth moves available through binding restrictions.",
    "passive.thousandRestraintsBody.effect.blocksEscape": "Cannot Escape or Assist. Other characters can still assist the owner.",
    "passive.subspaceMovement.effect.skipsTraps": "Movement does not trigger traps.",
    "binding.skunkBindings.name": "Skunk Bindings",
    "binding.skunkBindings.desc": "Living latex forms a connected set of Skunk bindings around the Head, Arms, Torso, and Legs.",
    "ui.library.skunk.spreading": "Spreading",
    "ui.library.skunk.transformation": "Skunkette Conversion",
    "ui.library.skunk.rescue": "Rescue",
    "ui.library.skunk.restoration": "Peak Restoration",
    "ui.library.skunk.collar": "Skunk Collar",
    "binding.skunkBindings.spreading": "Spread amount is based on binding removed. Escape and Assist spread latex onto the actor's [bindings:latexArms]. Escaping one's own Arms spreads it onto [bindings:latexHead] instead.",
    "binding.skunkBindings.transformation": "When all four body zones reach Overwhelming, the character becomes Incapacitated and converts into a hostile Skunkette.\nSkunk Queen will reclaim her collar from converted characters.\nDefeat the converted Skunkette to rescue the character, allowing them to reduce their bindings by half and rejoin the battle.",
    "binding.skunkBindings.rescue": "Defeat the linked [enemies:skunkette] to rescue the transformed character, remove the linked transformation, and reduce their bindings by half.",
    "binding.skunkBindings.restoration": "The four body bindings record their highest amounts. [moves:latexRegeneration] restores binding toward those peaks.",
    "binding.skunkBindings.collar": "Each tick adds 1/5 of the collar's amount, rounded up, to [bindings:latexHead], [bindings:latexArms], [bindings:latexTorso], and [bindings:latexLegs].\nThe collar does not share the body's escape spreading or peak restoration behavior.",
    "ui.library.hitCount": "{count} HITS",
    "ui.library.thisRound": "THIS ROUND",
    "ui.library.moveCooldown": "Move:",
    "ui.library.sharedCooldown": "Shared:",
    "ui.library.strongestBinding": "Strongest Binding",
    "ui.library.allBindings": "All Bindings",
    "ui.library.bodyZones": "Body Zones",
    "ui.library.bindingEach": "{amount} each",
    "ui.library.variableAmount": "Variable",
    "ui.library.bindingReduction": "−Escape potency ×2",
    "ui.library.modifiersHeading": "Modifiers",
    "ui.library.heal": "Heal",
    "ui.library.untilConsumed": "Until consumed",
    "ui.library.encounterDuration": "This encounter",
    "ui.library.oneChargeThisRound": "1 charge · this round",
    "ui.library.buffRules": "Buff rules",
    "ui.library.compulsionCooldown": "Compulsion shared cooldown: {count} rounds",
    "ui.library.selectedBinding": "Applies one selected binding.",
    "ui.library.severity": "Severity",
    "ui.library.spreadAmount": "Spread amount",
    "ui.library.recipient.self": "Self",
    "ui.library.recipient.allies": "Allies",
    "ui.library.recipient.enemies": "Enemies",
    "ui.library.recipient.boss": "Boss",
    "ui.library.recipient.enemy": "Enemy",
    "ui.library.recipient.players": "Players",
    "ui.library.recipient.field": "Field",
    "ui.library.recipient.selectedEnemy": "Target Enemy",
    "ui.library.recipient.enemyAllies": "Enemy Allies",
    "move.reflect.effect.reflect.note": "Reflects the next attack received this round. Lowers the incoming binding by half, rounding down. Deals damage to the attacking enemy equal to the original incoming binding amount.",
    "move.fairyReflect.effect.reflect.note": "Reflects the next attack received this round. Prevents the incoming binding and deals damage to the attacking enemy equal to its original amount.",
    "buff.empowerment.library": "Unlocks empowered moves if not already present. An empowered move consumes this buff.",
    "move.powerOfDenial.effect.defeat": "Target Non-Boss Enemy",
    "move.powerOfDenial.effect.binding": "Strongest Binding −100",
    "move.powerOfDenial.effect.binding.note": "Removes the strongest binding completely. Requires an existing binding on the ally.",
    "move.immolation.effect.binding": "All Bindings −50%",
    "move.immolation.effect.binding.note": "Rounds each removed amount up.",
    "move.obey.effect.refresh": "Target Ally's Action",
    "move.stop.effect.weaken": "Intentions −25%",
    "move.stop.effect.cancel": "Intentions",
    "move.attackMe.effect.retarget": "Intentions → [characters:matsuko]",
    "move.store.effect.binding": "Strongest Binding ↓",
    "move.store.effect.binding.note": "Uses escape potency with a ×2 assist factor, limited by free Subspace capacity.",
    "move.store.effect.resource": "Subspace +25 (up to capacity)",
    "move.store.effect.resource.note": "Remembers the removed binding type.",
    "move.store.effect.overflow": "Remembered Binding · Overflow",
    "move.store.effect.overflow.note": "Any of the 25 stored points exceeding capacity bind the caster instead.",
    "move.brace.effect.brace.note": "Absorbs the next enemy binding into Subspace and remembers its type. Any amount exceeding 100 capacity still binds the caster.",
    "move.release.effect.binding": "Remembered Binding",
    "move.release.effect.binding.note": "Adds half the Subspace spent on the ally, rounded up.",
    "move.release.effect.resource": "Subspace −25 / up to −50",
    "move.release.effect.resource.note": "Spends 25 when targeting an enemy, or up to 50 when targeting an ally.",
    "move.throwOff.effect.remove.note": "On a successful roll, removes Pounce from the victim and attacker.",
    "move.throwOff.effect.cooldown": "[moves:pounce] · 2 rounds",
    "move.throwOff.effect.cooldown.note": "On a successful roll.",
    "move.pounce.effect.victim": "Pounce",
    "move.pounce.effect.victim.note": "Adds [moves:throwOff].",
    "move.pounce.effect.attacker": "Pounce",
    "move.pounce.effect.attacker.note": "Defense −2. Accuracy: I +2, II +4, III +6, IV +8.",
    "move.pounce.effect.spray": "[moves:latexSpray]",
    "move.pounce.effect.spray.note": "Follow-up at effectiveness ≥1.75; on [difficulties:extreme], ≥0.95; on [difficulties:mythic], always.",
    "move.latexMist.effect.spread": "Latex Mist · Spread up to +5",
    "move.latexMist.effect.spread.note": "Shared roll determines Spread: +1 to +5.",
    "move.latexMist.effect.binding": "Existing Bindings ↑",
    "move.latexMist.effect.binding.note": "Hit: one existing binding × base amount × effectiveness. Critical: every existing binding × base amount × effectiveness ÷ 2.",
    "move.latexPuddle.effect.trap": "[traps:trapPuddle] ↑",
    "move.latexPuddle.effect.trap.note": "Adds the base amount × hit effectiveness.",
    "move.latexRegeneration.effect.restore": "Bindings → Recorded Peaks",
    "move.latexRegeneration.effect.restore.note": "Graze: restores the selected binding by base amount × effectiveness, capped at its peak. Hit: restores the selected binding to its peak. Critical: restores all bindings to their peaks.",
    "move.latexExplosion.effect.binding": "All Four Body Zones",
    "move.latexExplosion.effect.binding.note": "Each receives base amount × effectiveness.",
    "move.latexExplosion.effect.trap": "[traps:trapPuddle] +30",
    "move.latexExplosion.effect.trap.note": "On a miss or when no target is available.",
    "move.latexExplosion.effect.defeat": "Attacker",
    "move.latexExplosion.effect.defeat.note": "On a non-critical outcome. [difficulties:extreme] allows survival on contact; [difficulties:mythic] also allows survival on a miss.",
    "move.latexExplosion.effect.heal": "HP +60",
    "move.latexExplosion.effect.heal.note": "On a critical.",
    "move.healingMagic.effect.target": "HP +25% of maximum",
    "move.healingMagic.effect.target.note": "On a hit or critical.",
    "move.healingMagic.effect.others": "HP +25% of maximum",
    "move.healingMagic.effect.others.note": "On a critical, also heals damaged [enemies:skunkette], [enemies:skunk], and [enemies:fairy] allies, excluding the selected target.",
    "move.empoweringMagic.effect.target.note": "On a hit or critical.",
    "move.empoweringMagic.effect.others.note": "On a critical, also empowers other [enemies:skunkette], [enemies:skunk], [enemies:fairy], and [enemies:queen] allies.",
    "move.barrierMagic.effect.barrier.note": "Blocks damage applications: 1 charge on a graze, 2 on a hit, 3 on a critical. Each blocked application consumes one charge.",
    "move.latexRain.effect.binding": "Body Zones +10 each",
    "move.latexRain.effect.binding.note": "Per player: 2 zones on a graze, 3 on a hit, all 4 on a critical.",
    "move.callReinforcements.effect.spawn": "Enemy Reinforcements",
    "move.callReinforcements.effect.spawn.note": "Waves of [enemies:skunkette], [enemies:skunk], and later [enemies:fairy]. Later waves may grant Accuracy bonuses; enemy count and starting HP depend on the wave.",
    "move.latexRainmaker.effect.spawn": "[enemies:rainmaker]",
    "move.latexRainmaker.effect.spawn.note": "Starting HP and Accuracy bonuses depend on the construction wave.",
    "move.skunkPerfume.effect.defense.note": "Defense perfume alternative.",
    "move.skunkPerfume.effect.escape.note": "Escape perfume alternative.",
    "move.skunkPerfume.effect.heal": "HP +10% of maximum",
    "move.skunkPerfume.effect.heal.note": "Healing alternative: damaged [enemies:skunkette], [enemies:skunk], and [enemies:fairy] allies.",
    "binding.skunkBindings.spread.heavy": "25% → 50%",
    "binding.skunkBindings.spread.severe": "50% → 100%",
    "binding.skunkBindings.spread.overwhelming": "100% → 200%",
    "binding.skunkBindings.spreadScaling": "Each Spread point scales the removed-binding spread amount by 10%; positive Spread can also cause spreading below Heavy. Overflow beyond the main spread zone can reach the other body zones.",
    "binding.latexCollar.library": "Each tick adds 1/5 of the collar's amount, rounded up, to [bindings:latexHead], [bindings:latexArms], [bindings:latexTorso], and [bindings:latexLegs].\nThe collar does not use the body's normal escape-spreading or peak-restoration behavior.",
};
