import type { StringTable } from "../../src/ui/presentation/presentation";

/** Bracketed category:id tokens become campaign-scoped reference links in the Library. */
export const libraryEnglishStrings: StringTable = {
    "ui.library.grantedBy": "Granted By",
    "move.throwOff.source": "[enemies:skunkette]",
    "ui.library.baseMoves": "Base Moves",
    "ui.library.effects": "Effects",
    "ui.library.strategy": "Strategy",
    "ui.library.difficultyModifiers": "Difficulty Modifiers",
    "ui.library.target": "Target",
    "ui.library.duration": "Duration",
    "ui.library.modifiersAndRestrictions": "Modifiers & restrictions",
    "ui.library.triggerEffects": "Trigger Effects",
    "ui.library.triggerProbability": "Trigger Probability",
    "ui.library.outcomeProbability": "These chances are conditional on triggering at neutral Trap Avoidance and trap strength of 100 or less. Stronger traps and Trap Avoidance alter the distribution. Each binding application is capped by remaining strength.",
    "ui.library.probability": "{value}%",
    "ui.library.upTo": "Up to {amount}",
    "entity.skunkette.strategy": "If linked to a Pounce victim, uses [moves:latexSpray] on that victim.\nOtherwise, if [moves:pounce] is off cooldown, chooses a random valid character who is not already pounced.\nOtherwise, chooses [moves:latexMist] or [moves:latexSpray] with equal probability. Spray chooses a random valid character and a body-zone binding; falls back to Mist if no Spray target is available.",
    "entity.skunkette.rules": "Below 40% HP, gains Potency −4 and Defense −1.\nEach damaging application lowers [moves:pounce] severity by one; defeating the attacker removes Pounce.\nDefeating a Skunkette linked to a fully transformed character rescues that character and halves their bindings.",
    "entity.skunk.strategy": "Below 20% HP, uses [moves:latexExplosion] on the valid character with the highest total binding, or a random valid character if none is bound.\nOtherwise, may use [moves:latexPuddle]. The chance decreases as puddle strength rises: its roll must exceed current puddle strength + 25.\nOtherwise, may use [moves:latexRegeneration] on the character with the most binding removed below recorded peaks. Its roll must be lower than that total, then it chooses a random restorable binding.\nOtherwise, uses [moves:latexShower] on a random valid character and body zone, falling back to [moves:latexPuddle] if no attack target is available.",
    "entity.skunk.rules": "Crossing from at least 20% to below 20% HP while still alive cancels its intentions and immediately activates [moves:latexExplosion] against the attacker.",
    "entity.fairy.strategy": "Builds a list of eligible support actions: [moves:healingMagic] for damaged Skunkettes or Skunks; [moves:barrierMagic] for Skunkettes, Skunks, or Queens without a barrier; [moves:empoweringMagic] for Skunkettes, Skunks, or Queens.\nChooses uniformly among those eligible action types, then picks a random eligible target for that action.\nIf no support action is available, uses [moves:bindingMagic] on a random valid character and body zone.",
    "entity.rainmaker.strategy": "Uses [moves:latexRain] every turn, affecting the party.",
    "entity.queen.strategy": "If [moves:skunkCollar] is off cooldown and no valid character already has a collar, targets the character who has dealt the most damage to her. Chooses a random valid character if no damage has been recorded.\nOtherwise, if [moves:skunkPerfume] is off cooldown, chooses equally between its two debuffs; healing becomes a third equally likely option when a Skunkette, Skunk, or Fairy is damaged.\nOtherwise, uses [moves:skunkGun] on a random valid character and body zone. Falls back to Perfume when no valid gun target exists.",
    "entity.queen.rules": "Crossing 80%, 60%, 40%, and 20% HP activates [moves:callReinforcements] immediately.\nCrossing two-thirds and one-third HP activates [moves:latexRainmaker] immediately.\nEach threshold activates only the first time it is crossed. Encounter setup determines the next wave.",
    "binding.latexArms.light": "Simple latex gloves reach up to your elbows.",
    "binding.latexArms.moderate": "Thick latex gloves make it hard to manipulate things, and grow up to your shoulders.",
    "binding.latexArms.heavy": "Thick latex paw-shaped gloves cover your hands, making it nearly impossible to use them normally.",
    "binding.latexArms.severe": "Latex gloves fold over into half-length skunk paws, trapping your hands and arms against your shoulders.",
    "binding.latexArms.overwhelming": "Solid latex paws hold your hands and arms against your shoulders, leaving no room to move.",
    "binding.latexHead.light": "A light latex covering begins to surround your head.",
    "binding.latexHead.moderate": "The latex thickens around your mouth, making speech and mouth moves harder.",
    "binding.latexHead.heavy": "A thick latex hood presses around your head and mouth.",
    "binding.latexHead.severe": "The latex seals your mouth and encloses your head in a skunk-shaped hood.",
    "binding.latexHead.overwhelming": "A solid skunk hood holds your head and mouth tightly in place.",
    "binding.latexTorso.light": "A thin layer of living latex wraps around your torso.",
    "binding.latexTorso.moderate": "The latex thickens into a close-fitting suit around your torso.",
    "binding.latexTorso.heavy": "The suit tightens and begins to vibrate.",
    "binding.latexTorso.severe": "Dense vibrating latex constricts your torso.",
    "binding.latexTorso.overwhelming": "A solid vibrating suit encases your torso.",
    "binding.latexLegs.light": "Light latex stockings cover your legs.",
    "binding.latexLegs.moderate": "Thick latex stockings restrict your steps.",
    "binding.latexLegs.heavy": "The latex forms heavy skunk paws around your feet.",
    "binding.latexLegs.severe": "Dense latex holds your legs tightly together.",
    "binding.latexLegs.overwhelming": "Solid latex paws lock your legs in place.",
    "binding.latexCollar.light": "A living latex collar settles around your neck.",
    "binding.latexCollar.moderate": "The collar thickens, feeding latex onto your body.",
    "binding.latexCollar.heavy": "A heavy collar steadily supplies more living latex.",
    "binding.latexCollar.severe": "The dense collar presses firmly around your neck.",
    "binding.latexCollar.overwhelming": "A solid collar anchors the living latex around your neck.",
    "ui.library.title": "Library",
    "ui.library.intro": "Explore the characters, abilities, and mechanics in this campaign.",
    "ui.library.difficulties": "Difficulties",
    "ui.library.characters": "Characters",
    "ui.library.enemies": "Enemies",
    "ui.library.moves": "Moves",
    "ui.library.passives": "Passives",
    "ui.library.bindings": "Bindings",
    "ui.library.traps": "Traps",
    "ui.library.statuses": "Statuses",
    "ui.library.encounters": "Encounters",
    "ui.library.back": "Go Back",
    "ui.library.close": "Close Library",
    "ui.library.search": "Find an entry",
    "ui.library.count": "{count} entries",
    "ui.library.empty": "No entries in this category.",
    "ui.library.noResults": "No matching entries.",
    "ui.library.unavailable": "This entry is unavailable in this campaign.",
    "ui.library.attributes": "Base Attributes",
    "ui.library.mechanics": "Mechanics",
    "ui.library.related": "Related Entries",
    "ui.library.empoweredMoves": "Empowered Moves",
    "ui.library.startingResources": "Starting Resources",
    "ui.library.noResources": "No starting resources.",
    "ui.library.noPassives": "No innate passives.",
    "ui.library.noModifiers": "No modifiers.",
    "ui.library.noRestrictions": "No special restrictions.",
    "ui.library.noStatus": "No status at this threshold.",
    "ui.library.noMechanics": "No additional reference notes.",
    "ui.library.baseDamage": "Base Damage",
    "ui.library.baseAmount": "Base Effect Amount",
    "ui.library.baseNote": "Baseline per hit or effect, before combat modifiers, hit outcomes, and defense. Actual combat values may differ.",
    "ui.library.hits": "Base Hits",
    "ui.library.targeting": "Targeting",
    "ui.library.targetSide": "Target Side",
    "ui.library.targets": "Target Count",
    "ui.library.type": "Move Type",
    "ui.library.accuracy": "Base Accuracy",
    "ui.library.check": "Check",
    "ui.library.cooldowns": "Cooldowns Applied",
    "ui.library.cooldown": "{count} rounds",
    "ui.library.freeOnHit": "Does not consume the action on a successful hit.",
    "ui.library.alwaysAvailable": "Always available in the move list.",
    "ui.library.restrictions": "Restrictions",
    "ui.library.allowed": "Allows {type} moves, even if another status blocks that type.",
    "ui.library.blocked": "Blocks {type} moves.",
    "ui.library.immunities": "Status Immunities",
    "ui.library.intensity": "Intensity {level}",
    "ui.library.intensityNote": "Each row shows the full effects at that intensity, not extra effects to add to earlier rows. The highest intensity of each status applies; duplicate sources do not stack.",
    "ui.library.progression": "Severity Progression",
    "ui.library.progressionNote": "Each threshold replaces the previous threshold’s status list. Status intensity is separate from binding severity.",
    "ui.library.range": "{min}–{max}",
    "ui.library.belowThreshold": "Below {min}, the binding has no severity. The first tier begins at {min}.",
    "ui.library.growthNote": "Binding added beyond the Overwhelming threshold is reduced to 10% of the overflowing amount, up to the maximum binding cap.",
    "ui.library.maximum": "Maximum binding: {max}.",
    "ui.library.rank": "Rank",
    "ui.library.hp": "Base HP",
    "ui.library.defense": "Base Defense",
    "ui.library.playerModifiers": "Player Modifiers",
    "ui.library.enemyModifiers": "Enemy Modifiers",
    "ui.library.specialRules": "Special Rules",
    "ui.library.setup": "Starting Effects",
    "ui.library.challenge": "Challenge",
    "ui.library.usedBy": "Used By",
    "ui.library.resource": "{name}: {value}",
    "ui.library.resourceRange": "{name}: {value} / {max}",
    "ui.library.severityName": "{difficulty} · {severity}",
    "ui.library.none": "None",
    "ui.library.all": "All",
    "ui.library.self": "Self / no selected target",
    "ui.library.either": "Players or enemies",
    "ui.library.player": "Players",
    "ui.library.enemy": "Enemies",
    "ui.library.untargeted": "No selected target",
    "ui.library.willpower": "Willpower",
    "ui.library.accuracyCheck": "Accuracy",
    "ui.library.light": "Easy",
    "ui.library.moderate": "Medium",
    "ui.library.heavy": "Hard",
    "ui.library.severe": "Extreme",
    "ui.library.overwhelming": "Impossible",
    "ui.library.noCheck": "No accuracy roll",
    "entity.ko.library": "Uses [moves:fairyTransformation] to unlock empowered moves. Each empowered move consumes empowerment.",
    "entity.matsuko.library": "Flame attacks combine accuracy or potency bonuses with damage. Empowered flame moves consume empowerment from [moves:fairyEmpowerment].\n[moves:immolation] reduces every binding but permanently replaces flame moves with [moves:punch] and [moves:kick] for the encounter.\nCompulsions share cooldowns. A successful compulsion does not consume Matsuko’s action.",
    "entity.hinari.library": "Subspace starts empty and holds up to 100. More stored material reduces the hit count of [moves:rockfall] and [moves:fairyRockfall].\n[moves:store] and [moves:brace] fill Subspace; [moves:release] empties it. Full Subspace prevents Rockfall, Store, and Brace.",
    "passive.thousandRestraintsBody.library": "Accuracy penalties and other flags still apply. Other characters can still assist the owner unless their own restrictions prevent it.",
    "move.telekinesis.library": "Deals baseline damage to one enemy. Mouth restrictions and accuracy modifiers can affect its use and result.",
    "move.fairyTelekinesis.library": "Consumes empowerment after use.",
    "move.starlightBindings.library": "This is an enemy debuff; it does not apply the player [statuses:bound] status.",
    "move.fairyStarlightBindings.library": "Consumes empowerment after use.",
    "move.reflect.library": "Protects the caster from the next binding application by an enemy. It deals damage to that enemy equal to the incoming binding amount and halves the binding amount, rounding down.\nThe protection has one charge.",
    "move.fairyReflect.library": "Protects the caster from the next binding application by an enemy. It deals damage to that enemy equal to the incoming amount and prevents that binding application.\nThe protection has one charge and consumes empowerment when cast.",
    "move.fairyTransformation.library": "Unlocks empowered moves if empowerment is not already present. Using an empowered move consumes empowerment.",
    "move.fairyEmpowerment.library": "Unlocks empowered moves for other party members. Consumes the caster’s empowerment.",
    "move.powerOfDenial.library": "On a character, removes their strongest binding completely. Requires at least one binding.\nOn an enemy, defeats it outright. Bosses are invalid targets.\nAfter use, this move is sealed for the rest of the encounter.",
    "move.punch.library": "Deals baseline damage to one enemy with an Arms move.\nAdded by [moves:immolation] after burnout.",
    "move.kick.library": "Deals baseline damage to one enemy with a Legs move.\nAdded by [moves:immolation] after burnout.",
    "move.fairyWhiteFlame.library": "Consumes empowerment after use.",
    "move.fairyPhoenixKick.library": "Consumes empowerment after use.",
    "move.immolation.library": "Removes half of each of the caster’s bindings, rounding the removed amount up.\nBurnout seals [moves:whiteFlame], [moves:fairyWhiteFlame], [moves:phoenixKick], [moves:fairyPhoenixKick], and Immolation for the encounter, and adds [moves:punch] and [moves:kick].",
    "move.obey.library": "Refreshes an allied character who has already acted, giving them another action. Cannot target someone already affected by Servitude.\nApplies [statuses:servitude] for 2 rounds, preventing Escape.",
    "move.stop.library": "Cancels a non-boss enemy’s intentions. Against a boss, weakens intentions by 25% instead.",
    "move.attackMe.library": "Retargets enemy intentions toward the caster and gives the caster Defense +3 for 1 round.\nA successful hit preserves the caster’s action and applies shared compulsion cooldowns.",
    "move.rockfall.library": "Starts at 4 hits. The hit count falls as Subspace fills; full Subspace prevents use.\nDoes not spend Subspace. Use [moves:release] to make room for more hits.",
    "move.fairyRockfall.library": "Starts at 6 hits. The hit count falls as Subspace fills; full Subspace prevents use.\nConsumes empowerment after use.",
    "move.store.library": "Requires Subspace below 100 and a character with at least one binding.\nReduces the target’s strongest binding using escape potency with a ×2 assist factor, limited by free Subspace capacity.\nStores up to 25 Subspace and remembers that binding type. Any overflow from those 25 points binds the caster instead.",
    "move.brace.library": "Requires Subspace below 100.\nAbsorbs the next enemy binding application into Subspace, remembering its type. Any amount exceeding the 100 capacity still binds the caster.\nThe protection has one charge.",
    "move.release.library": "Requires at least 25 Subspace and a remembered binding type.\nOn an enemy: spends 25 Subspace and applies Defense −2 and Accuracy −2 for 2 rounds.\nOn a character: spends up to 50 Subspace and applies half that amount, rounded up, as the remembered binding.",
    "move.latexSpray.library": "Applies a selected body-zone binding. The base effect amount is scaled by the hit outcome and combat modifiers.",
    "move.latexShower.library": "Applies a selected body-zone binding. The base effect amount is scaled by the hit outcome and combat modifiers.",
    "move.bindingMagic.library": "Applies a selected body-zone binding. The base effect amount is scaled by the hit outcome and combat modifiers.",
    "move.skunkGun.library": "Applies a selected body-zone binding. The base effect amount is scaled by the hit outcome and combat modifiers.",
    "move.skunkCollar.library": "Applies [bindings:latexCollar], which grows the four main body bindings each tick.",
    "move.pounce.library": "Links attacker and victim. All four severity levels apply [statuses:immobilized] and add [moves:throwOff] to the victim.\nSeverity I: attacker Accuracy +2, Defense −2. Severity II: attacker Accuracy +4, Defense −2; victim Accuracy −1.\nSeverity III: attacker Accuracy +6, Defense −2; victim Accuracy −2 and [statuses:stunned]. Severity IV: attacker Accuracy +8, Defense −2; victim [statuses:helpless].\nDamaging the attacker lowers pounce severity by one level; defeating it removes the link. Higher hit effectiveness creates stronger pounces.\nStrong criticals can trigger [moves:latexSpray]. [difficulties:extreme] and [difficulties:mythic] make follow-up attacks more frequent.",
    "move.throwOff.library": "Available to a victim of [moves:pounce]. On a successful roll, removes both linked Pounce effects and starts the attacker’s Pounce cooldown.",
    "move.latexMist.library": "Applies a 1-round Spread penalty of up to +5 to all players.\nA hit strengthens one existing binding; a critical strengthens all existing bindings using the move’s base amount and effectiveness.",
    "move.latexPuddle.library": "Adds [traps:trapPuddle] to the field using the base effect amount and hit effectiveness.",
    "move.latexRegeneration.library": "Restores bindings toward their recorded peak values.\nGraze: restores part of the selected binding, up to its peak. Hit: restores the selected binding to its peak. Critical: restores all bindings to their peaks.",
    "move.latexExplosion.library": "Applies binding to all four body zones of one target.\nOn a miss, adds 30 [traps:trapPuddle] and normally defeats the attacker. On a non-critical hit, normally defeats the attacker. A critical heals the attacker for 60 HP.\n[difficulties:extreme] allows survival on a hit; [difficulties:mythic] allows survival even on a miss.",
    "move.healingMagic.library": "Restores 25% of the selected enemy’s maximum HP on a hit or critical.\nA critical also heals damaged [enemies:skunkette], [enemies:skunk], and [enemies:fairy] allies by 25% of their maximum HP.",
    "move.empoweringMagic.library": "Gives the selected enemy Potency +5 for 1 round.\nA critical also empowers other [enemies:skunkette], [enemies:skunk], [enemies:fairy], and [enemies:queen] allies.",
    "move.barrierMagic.library": "Blocks incoming damage applications with a limited number of charges: 1 on a graze, 2 on a hit, 3 on a critical.\nEach blocked application consumes one charge.",
    "move.latexRain.library": "Applies 10 binding to 2 body zones on a graze, 3 on a hit, and all 4 on a critical, for each player target.",
    "move.callReinforcements.library": "Summons waves of [enemies:skunkette], [enemies:skunk], and later [enemies:fairy] allies.\nThe boss triggers reinforcement waves when crossing 80%, 60%, 40%, and 20% HP for the first time. Encounter setup determines which wave comes next.",
    "move.latexRainmaker.library": "Summons an [enemies:rainmaker]. Later waves can grant stronger accuracy modifiers.\nThe boss triggers construction when crossing two-thirds and one-third HP for the first time. Encounter setup determines the construction wave.",
    "move.skunkPerfume.library": "Uses a Willpower check. Can apply Defense −2 or Escape −2 to player targets for 4 rounds.\nAlternatively heals damaged [enemies:skunkette], [enemies:skunk], and [enemies:fairy] allies for 10% of their maximum HP.",
    "entity.skunkette.library": "Prioritizes spraying a linked Pounce victim, otherwise attempts [moves:pounce] when available and alternates [moves:latexMist] and [moves:latexSpray].\nBelow 40% HP, victim resistance gives Potency −4 and Defense −1.\nDefeating the Skunkette linked to a fully skunked character rescues them and reduces their bindings by half.",
    "entity.skunk.library": "Creates [traps:trapPuddle] and uses [moves:latexRegeneration] to undo escape progress.\nCrossing below 20% HP while still alive interrupts its current intentions and immediately triggers [moves:latexExplosion] against the attacker.",
    "entity.fairy.library": "Supports allies with [moves:healingMagic], [moves:barrierMagic], and [moves:empoweringMagic]; uses [moves:bindingMagic] when no support action is available.",
    "entity.rainmaker.library": "Uses [moves:latexRain] every turn.\nDefeat adds 50 [traps:trapPuddle] on [difficulties:extreme], or 100 on [difficulties:mythic].",
    "entity.queen.library": "Uses [moves:skunkCollar] when no player has a collar, prioritizing the player who has dealt the most damage to her.\nUses [moves:skunkPerfume] when available; otherwise attacks with [moves:skunkGun].\nCrossing HP thresholds triggers [moves:callReinforcements] and [moves:latexRainmaker]. Those triggers only occur the first time each threshold is crossed.",
    "binding.latexHead.library": "Part of the living latex set, along with [bindings:latexArms], [bindings:latexTorso], and [bindings:latexLegs].\nEscape spreads material onto the escaping character’s arms; spread increases at Heavy, Severe, and Overwhelming severity. Overflow can reach other body zones.\nWhen all four zones reach Overwhelming, the character becomes [statuses:incapacitated] and spawns a linked [enemies:skunkette]. Defeating the linked enemy rescues the character.",
    "binding.latexArms.library": "Escape from one’s own arm binding spreads material onto [bindings:latexHead]; other escape or assist attempts spread material onto the actor’s arms.\nHeavy: spread starts at 25% of the removed binding and rises toward 50%. Severe: 50% toward 100%. Overwhelming: 100% toward 200%.\nSpread modifiers scale those amounts by 10% per point and can cause spreading even below Heavy. Overflow beyond the main spread zone can reach other body zones.\nAt Overwhelming on all four body zones, the character becomes [statuses:incapacitated] and spawns a linked [enemies:skunkette].",
    "binding.latexTorso.library": "Escaping spreads material onto the actor’s [bindings:latexArms]. Spread increases at Heavy, Severe, and Overwhelming severity.\n[statuses:vibrating] prevents bonus escapes; its escape penalty increases as the torso binding intensifies.\nAt Overwhelming on all four body zones, the character becomes [statuses:incapacitated] and spawns a linked [enemies:skunkette].",
    "binding.latexLegs.library": "Escaping spreads material onto the actor’s [bindings:latexArms]. Spread increases at Heavy, Severe, and Overwhelming severity.\nAt Overwhelming on all four body zones, the character becomes [statuses:incapacitated] and spawns a linked [enemies:skunkette].",
    "binding.latexCollar.library": "Each tick applies one-fifth of the collar’s current amount, rounded up, to [bindings:latexHead], [bindings:latexArms], [bindings:latexTorso], and [bindings:latexLegs].\nThe collar does not use the other latex bindings’ escape spreading or peak restoration behavior.",
    "trap.trapPuddle.library": "Moving characters check for traps; standing characters skip that movement risk. [passives:subspaceMovement] ignores traps.\nA trap triggers when its modified roll is below the remaining puddle strength. Trap Avoidance modifies that roll.\nTriggered puddles lose the strength used by their binding applications. The amounts shown above are upper bounds; each application is limited by the remaining strength."
};
