import { StringTable } from "../../src/ui/presentation/presentation";

export const skunkEnglishStrings: StringTable = {
    "entity.skunkette.generic": "Skunkette",
    "entity.skunk.generic": "Skunk",
    "entity.fairy.generic": "Fairy",
    "entity.rainmaker.generic": "Rainmaker",
    "entity.skunkette.name": "Skunkette {index}",
    "entity.skunk.name": "Skunk {index}",
    "entity.fairy.name": "Fairy {index}",
    "entity.rainmaker.name": "Rainmaker {index}",

    "entity.queen.name": "Skunk Queen",
    "entity.empress.name": "Skunk Empress",
    "entity.goddess.name": "Skunk Goddess",

    "entity.skunketteQueen.name": "Skunkette Queen",
    "entity.skunkEmpress.name": "Skunk Empress",

    "entity.skunketteKo.name": "Skunkette Ko",
    "entity.skunketteMatsuko.name": "Skunkette Matsuko",
    "entity.skunketteHinari.name": "Skunkette Hinari",

    "entity.skunkette.desc": "An unfortunate girl that has been trapped on her elbows and knees by a suit of living latex. The latex itself controls her body, and she can only watch on as she assaults anyone nearby, trying to create more skunks.",
    "entity.skunk.desc": "A cute forest animal... with a high gloss sheen. It sprays latex on anything that threatens it, and it covers the area in traps!",
    "entity.fairy.desc": "A tiny skunk with fairy wings. Just what kind of experiment created this being?",
    "entity.rainmaker.desc": "A creation of an insane genius. It sprays latex everywhere, covering everyone in the vicinity!",
    "entity.queen.desc": "A girl obsessed with latex skunks, she is their creator! She wishes to turn every girl in the world into a cute skunk and rule over them as their queen!",
    "entity.empress.desc": "This is the original creator of the latex skunk technology, unlike the usurper in the woods.",
    "entity.goddess.desc": "The Goddess of the Realms, here to offer the ultimate challenge after saving you from the Skunk Empress.",
    "entity.skunketteQueen.desc": "The former Skunk Queen, reduced to a minion after her failure.",
    "entity.skunkEmpress.desc": "The former Skunk Empress, reduced to a minion after her failure.",

    "difficulty.extreme.skunkette": "Gets a followup Latex Spray on strong hits as well as criticals.",
    "difficulty.extreme.skunk": "Survives Latex Explosion when it hits a target.",
    "difficulty.extreme.fairy": "Has a 50% chance to use Binding Magic as an extra attack each turn.",
    "difficulty.extreme.queen": "Uses Skunk Gun as an extra attack each turn below 50% HP.",
    "difficulty.extreme.rainmaker": "Explodes into 50 Latex Puddles when defeated.",
    "difficulty.mythic.skunkette": "Gets a followup Latex Spray on any hit.",
    "difficulty.mythic.skunk": "Survives Latex Explosion whether it hits or misses.",
    "difficulty.mythic.fairy": "Uses Binding Magic as an extra attack each turn.",
    "difficulty.mythic.queen": "Uses Skunk Gun as an extra attack each turn.",
    "difficulty.mythic.rainmaker": "Explodes into 100 Latex Puddles when defeated.",

    "buff.ambushed.name": "Ambushed!",
    "buff.ambushed.desc": "...",

    // Skunkette
    "move.latexSpray.name": "Latex Spray",
    "move.latexSpray.desc": "Spray living latex onto one body zone.",
    "move.pounce.name": "Pounce",
    "move.pounce.desc": "Pin and link a victim, with stronger restrictions at higher severity.",
    "move.latexMist.name": "Latex Mist",
    "move.latexMist.desc": "Coat the party in mist that increases escape spreading and strengthens bindings.",
    "move.throwOff.name": "Throw Off",
    "move.throwOff.desc": "Throw off a linked Pounce attacker.",

    "buff.pounce.name": "Pounce",
    "buff.pounce.desc": "...",
    "buff.pounce.allow": "Adds Throw Off",
    "buff.latexMist.name": "Latex Mist",
    "buff.latexMist.desc": "...",
    "buff.resistance.name": "Victim Resistance",
    "buff.resistance.desc": "...",
    "buff.skunked.name": "Fully Skunked",
    "buff.skunked.desc": "...",

    // Skunk
    "move.latexShower.name": "Latex Shower",
    "move.latexShower.desc": "Shower a character’s body zone with living latex.",
    "move.latexPuddle.name": "Latex Puddle",
    "move.latexPuddle.desc": "Add latex puddles to the field.",
    "move.latexRegeneration.name": "Latex Regeneration",
    "move.latexRegeneration.desc": "Restore living latex toward its previous peak.",
    "move.latexExplosion.name": "Latex Explosion",
    "move.latexExplosion.desc": "Explode into latex across all of a target’s body zones.",

    // Fairy
    "move.bindingMagic.name": "Binding Magic",
    "move.bindingMagic.desc": "Use magic to strengthen a body-zone binding.",
    "move.healingMagic.name": "Healing Magic",
    "move.healingMagic.desc": "Heal an enemy ally.",
    "move.empoweringMagic.name": "Empowering Magic",
    "move.empoweringMagic.desc": "Increase the potency of enemy allies.",
    "move.barrierMagic.name": "Barrier Magic",
    "move.barrierMagic.desc": "Shield an enemy from incoming damage.",

    "buff.empoweringMagic.name": "Empowering Magic",
    "buff.empoweringMagic.desc": "...",
    "buff.barrierMagic.name": "Barrier Magic",
    "buff.barrierMagic.desc": "...",

    // Rainmaker
    "move.latexRain.name": "Latex Rain",
    "move.latexRain.desc": "Rain latex across multiple body zones of every player.",

    "buff.extraSprayers.name": "Extra Sprayers",
    "buff.extraSprayers.desc": "...",

    // Queen
    "move.skunkGun.name": "Skunk Gun",
    "move.skunkGun.desc": "Fire latex at a selected body zone.",
    "move.skunkCollar.name": "Skunk Collar",
    "move.skunkCollar.desc": "Apply a collar that steadily grows other latex bindings.",
    "move.callReinforcements.name": "Call Reinforcements",
    "move.callReinforcements.desc": "Summon the next wave of enemy allies.",
    "move.latexRainmaker.name": "Construct Rainmaker",
    "move.latexRainmaker.desc": "Construct a Rainmaker to spray the party.",
    "move.skunkPerfume.name": "Skunk Perfume",
    "move.skunkPerfume.desc": "Apply weakening perfume or heal enemy allies.",

    "buff.defensePerfume.name": "Defense Perfume",
    "buff.defensePerfume.desc": "...",
    "buff.escapePerfume.name": "Escape Perfume",
    "buff.escapePerfume.desc": "...",
    "buff.empressMight.name": "Empress's Might",
    "buff.empressMight.desc": "...",
    "buff.goddessMight.name": "Goddess's Might",
    "buff.goddessMight.desc": "...",

    // Bindings
    "binding.latexHead.name": "Skunk Head",
    "binding.latexHead.short": "Head",
    "binding.latexHead.compact": "H",
    "binding.latexHead.desc": "Living latex that restricts mouth moves and lowers willpower.",
    "binding.latexArms.name": "Skunk Arms",
    "binding.latexArms.short": "Arms",
    "binding.latexArms.compact": "A",
    "binding.latexArms.desc": "Living latex that progressively restricts arm moves and assistance.",
    "binding.latexTorso.name": "Skunk Torso",
    "binding.latexTorso.short": "Torso",
    "binding.latexTorso.compact": "T",
    "binding.latexTorso.desc": "Living latex that reduces defense and escape capability.",
    "binding.latexLegs.name": "Skunk Legs",
    "binding.latexLegs.short": "Legs",
    "binding.latexLegs.compact": "L",
    "binding.latexLegs.desc": "Living latex that reduces defense, trap avoidance, and leg accuracy.",
    "binding.latexCollar.name": "Skunk Collar",
    "binding.latexCollar.short": "Collar",
    "binding.latexCollar.compact": "C",
    "binding.latexCollar.desc": "A controlling collar that lowers willpower and grows other latex bindings.",

    // Trap
    "trap.trapPuddle.name": "Latex Puddle",
    "trap.trapPuddle.desc": "A field hazard that consumes puddles to bind moving characters.",

    // Encounters
    "encounter.plains_1.name": "Fight with Skunkettes",
    "encounter.plains_1.desc": "Face three Skunkettes and learn to manage the four body-zone bindings.",
    "encounter.plains_2.name": "Fight with Skunks",
    "encounter.plains_2.desc": "Face two Skunkettes and two Skunks on a field with 50 latex puddles.",
    "encounter.plains_3.name": "Fight with Skunk Queen",
    "encounter.plains_3.desc": "Challenge the Skunk Queen, whose collar and reinforcements create growing pressure.",
    "encounter.forest_1.name": "Skunkette Ambush",
    "encounter.forest_1.desc": "Three Skunkettes and a Fairy ambush the party. All characters skip the opening turn.",
    "encounter.forest_2.name": "Fight in the Latex Swamp",
    "encounter.forest_2.desc": "Two Skunkettes, two Skunks, and a Fairy defend a field saturated with 100 latex puddles.",
    "encounter.forest_3.name": "Skunk Queen's Rematch",
    "encounter.forest_3.desc": "The Skunk Queen returns with two Skunkettes, a Fairy, and 100 latex puddles.",
    "encounter.tower_1.name": "Skunk Empress's Scheme",
    "encounter.tower_1.desc": "The Skunk Empress opens with strengthened forces, collars on the party, and an ambush.",
    "encounter.tower_2.name": "Goddess's Assistance",
    "encounter.tower_2.desc": "The Goddess assists the party against the Skunk Empress’s strengthened forces.",
    "encounter.tower_3.name": "Goddess's Resurgence",
    "encounter.tower_3.desc": "Stronger divine assistance gives the party another chance against the Skunk Empress.",
    "encounter.outside.name": "Goddess's Trial",
    "encounter.outside.desc": "Face the Goddess with the former rulers serving as her minions.",

};

