import { StringTable } from "../../src/ui/presentation/presentation";


export const systemStrings: StringTable = {
    "ui.encounterPicker.title": "Ko-chan’s Quest",
    "ui.encounter.challenge": "Challenge",
    "ui.encounter.challengeAccessible": "{stars} of 5 stars",
    "ui.encounter.bestClear": "Best Clear",
    "ui.encounter.uncleared": "---",
    "ui.encounter.description": "Description",
    "ui.encounter.enemies": "Enemies",
    "ui.encounter.specialRules": "Special Rules",
    "ui.encounter.start": "Start Encounter",
    "ui.encounter.chooseDifficulty": "Choose Difficulty",
    "ui.difficulty.title": "Difficulty",
    "ui.difficulty.globalEffects": "Global Effects",
    "ui.difficulty.enemyColumn": "Enemy",
    "ui.difficulty.changeColumn": "Change",
    "buff.difficultyModifier.name": "Difficulty Modifier",
    "ui.encounter.hp": "HP: {hp}",
    "ui.enemyRank.boss": "Boss",
    "ui.enemyRank.enemy": "Enemy",
    "ui.enemyRank.minion": "Minion",
    "phase.player.name": "Player",
    "phase.enemy.name": "Enemy",

    "stance.standing.name": "Standing",
    "stance.moving.name": "Moving",

    "entity.allies.name": "Allies",
    "entity.enemies.name": "Enemies",

    "ui.action.ready": "Ready",
    "ui.action.acted": "Acted",
    "ui.action.skipped": "Skipped",
    "ui.action.unavailable": "Unavailable",
    "ui.battleOverview.endTurn": "End Turn",
    "ui.battleOverview.enemies": "Enemies",
    "ui.battleOverview.enemiesRemaining": "{count} remaining",
    "ui.battleOverview.gameLog": "Game Log",
    "ui.battleOverview.noEncounter": "Battle",
    "ui.battleOverview.party": "Party",
    "ui.battleOverview.partyCount": "{active} / {total}",
    "ui.battleOverview.phase": "{phase} Phase",
    "ui.battleOverview.round": "Round {round}",
    "ui.battleOverview.settings": "Settings",
    "ui.combatHeader.character": "Character",
    "ui.combatHeader.escape": "Escape",
    "ui.combatHeader.gameLog": "Game Log",
    "ui.combatHeader.targeting": "Targeting",
    "ui.characterDetails.back": "Go Back",
    "ui.characterDetails.bindingValue": "{value}",
    "ui.characterDetails.bindingsHeading": "Bindings / {count} Zones",
    "ui.characterDetails.blocked": "Blk",
    "ui.characterDetails.changeStance": "Change Stance",
    "ui.characterDetails.stanceTransitionIndicator": "\u2192",
    "ui.characterDetails.stanceTransition": "→ {stance}",
    "ui.characterDetails.commandsHeading": "Commands / {character}",
    "ui.characterDetails.cooldown": "Cooldown {count}",
    "ui.characterDetails.effectModifier": "{modifier} {value}",
    "ui.characterDetails.buffsHeading": "Buffs",
    "ui.characterDetails.escape": "Escape",
    "ui.characterDetails.noEscapeTargets": "No valid escape targets.",
    "ui.characterDetails.modifierValue": "{value}",
    "ui.characterDetails.rosterLabel": "Party roster",
    "ui.characterDetails.rounds": "{count} Rounds",
    "ui.characterDetails.selectMove": "Select Move",
    "ui.characterDetails.shortcut": "[{shortcut}]",
    "ui.characterDetails.statusHeading": "Status & Capabilities",
    "ui.characterDetails.statusValue": "{status} {value}",
    "ui.characterDetails.subtitle": "{character} / {difficulty} View",
    "ui.characterDetails.tagAlly": "Ally",
    "ui.characterDetails.tagAoe": "AOE",
    "ui.characterDetails.tagBuff": "Buff",
    "ui.characterDetails.tagDamage": "Damage",
    "ui.characterDetails.tagDebuff": "Debuff",
    "ui.characterDetails.tagEnemy": "Enemy",
    "ui.characterDetails.tagEscape": "Escape",
    "ui.characterDetails.tagOnetime": "One Time",
    "ui.characterDetails.tagRefresh": "Refresh",
    "ui.characterDetails.tagHeal": "Heal",
    "ui.characterDetails.tagDefeat": "Defeat",
    "ui.characterDetails.tagSpawn": "Spawn",
    "ui.characterDetails.tagTrap": "Trap",
    "ui.characterDetails.tagRetarget": "Retarget",
    "ui.characterDetails.tagHits": "{count} Hits",
    "ui.characterDetails.tagSelf": "Self",
    "ui.characterDetails.tagFree": "Free",
    "ui.characterDetails.tagBonusEscape": "Bonus Escape",
    "ui.characterDetails.tagBonusEligible": "Bonus: Eligible",
    "ui.characterDetails.tagBonusStanding": "Bonus: Standing",
    "ui.characterDetails.tagBonusBlocked": "Bonus: Blocked",
    "ui.escape.assist": "Assist {character}'s {binding}",
    "ui.escape.tagSpread": "Spread",
    "ui.escape.use": "Use Escape",
    "ui.effects.none": "No effects",
    "ui.effects.more": "+{count} more",
    "ui.intentions.more": "+{count}",
    "ui.intentions.moreAccessible": "{count} more intentions",
    "ui.intentions.all": "ALL",
    "ui.linkedEntity.linkedTo": "Linked to {character}",
    "ui.partyCard.blockedCapabilities": "Blocked capabilities",
    "ui.partyCard.bindings": "Bindings",
    "ui.partyCard.effects": "Effects",
    "ui.partyCard.resourceValue": "{resource}: {value}",
    "ui.targeting.actionEffects": "Action Effects",
    "ui.targeting.addMove": "Add {move}",
    "ui.targeting.allEnemies": "Target / All Enemies",
    "ui.targeting.allPlayers": "Target / All Players",
    "ui.targeting.allTargets": "Target / All Targets",
    "ui.targeting.back": "Go Back",
    "ui.targeting.bindingAmount": "{amount} Binding",
    "ui.targeting.blockMove": "Block {move}",
    "ui.targeting.chance": "{band} · {chance}%",
    "ui.targeting.characterSummary": "{action} · {stance}",
    "ui.targeting.chooseMany": "Target / Choose {count}",
    "ui.targeting.chooseOne": "Target / Choose One",
    "ui.targeting.damageAmount": "{amount} damage",
    "ui.targeting.damageRange": "{min}–{max}",
    "ui.targeting.dataAmount": "{name} {amount}",
    "ui.targeting.effectAccuracy": "Accuracy",
    "ui.targeting.effectAddBuff": "Add Buff",
    "ui.targeting.effectAddDebuff": "Add Debuff",
    "ui.targeting.effectBinding": "Binding",
    "ui.targeting.effectBuff": "Buff",
    "ui.targeting.effectDamage": "Damage",
    "ui.targeting.effectMove": "Move",
    "ui.targeting.effectTrap": "Trap",
    "ui.targeting.effectData": "Data",
    "ui.targeting.effectResource": "Resource",
    "ui.targeting.effectCancel": "Cancel",
    "ui.targeting.effectWeaken": "Weaken",
    "ui.targeting.effectRetarget": "Retarget",
    "ui.targeting.effectRefresh": "Refresh",
    "ui.targeting.effectRemoveBuff": "Remove Buff",
    "ui.targeting.effectRemoveDebuff": "Remove Debuff",
    "ui.targeting.operationDefeat": "Defeat",
    "ui.targeting.operationSpawn": "Spawn",
    "ui.targeting.percentage": "{value}%",
    "ui.targeting.trapAmount": "Amount {amount}",
    "ui.targeting.use": "Use {move}",
    "ui.targeting.value": "{current} / {max}",

    "moveType.arms.compact": "Arms",
    "moveType.mouth.compact": "Mouth",
    "moveType.legs.compact": "Legs",
    "moveType.none.compact": "None",

    "difficulty.casual.name": "Casual",
    "difficulty.casual.desc": "Player characters receive bonuses to better be able to face the enemy.",
    "difficulty.standard.name": "Standard",
    "difficulty.standard.desc": "The standard experience with no modifications to gameplay.",
    "difficulty.veteran.name": "Veteran",
    "difficulty.veteran.desc": "Enemies are stronger and more efficient with their attacks.",
    "difficulty.extreme.name": "Extreme",
    "difficulty.extreme.desc": "Stronger enemies with additional unique powers.",
    "difficulty.mythic.name": "Mythic",
    "difficulty.mythic.desc": "Stronger enemies with even stronger unique powers.",

    "bindingLevel.none.name": "None",
    "bindingLevel.light.name": "Light",
    "bindingLevel.moderate.name": "Moderate",
    "bindingLevel.heavy.name": "Heavy",
    "bindingLevel.severe.name": "Severe",
    "bindingLevel.overwhelming.name": "Overwhelming",
    "bindingLevel.max.name": "Maximum",

    "hitBand.miss.name": "Miss",
    "hitBand.graze.name": "Graze",
    "hitBand.hit.name": "Hit",
    "hitBand.crit.name": "Crit",
    "hitBand.none.name": "None",

    "battleState.ongoing.name": "Ongoing",
    "battleState.victory.name": "Victory",
    "battleState.defeat.name": "Defeat",

    "status.bound.name": "Bound",
    "status.bound.desc": "...",
    "status.gagged.name": "Gagged",
    "status.gagged.desc": "...",
    "status.hobbled.name": "Hobbled",
    "status.hobbled.desc": "...",
    "status.vibrating.name": "Vibrating",
    "status.vibrating.desc": "...",
    "status.submissive.name": "Submissive",
    "status.submissive.desc": "...",
    "status.breathless.name": "Breathless",
    "status.breathless.desc": "...",
    "status.blinded.name": "Blinded",
    "status.blinded.desc": "...",
    "status.immobilized.name": "Immobilized",
    "status.immobilized.short": "Immob",
    "status.immobilized.desc": "...",
    "status.helpless.name": "Helpless",
    "status.helpless.desc": "...",
    "status.stunned.name": "Stunned",
    "status.stunned.desc": "...",
    "status.incapacitated.name": "Incapacitated",
    "status.incapacitated.short": "Incap",
    "status.incapacitated.desc": "...",
    "status.servitude.name": "Blocks Escape",
    "status.servitude.desc": "...",

    "modifier.hitarms.name": "Accuracy(Arms)",
    "modifier.hitarms.compact": "HIT",
    "modifier.hitmouth.name": "Accuracy(Mouth)",
    "modifier.hitmouth.compact": "HIT",
    "modifier.hitlegs.name": "Accuracy(Legs)",
    "modifier.hitlegs.compact": "HIT",
    "modifier.hit.name": "Accuracy",
    "modifier.hit.compact": "HIT",
    "modifier.defense.name": "Defense",
    "modifier.defense.compact": "DEF",
    "modifier.escape.name": "Escape",
    "modifier.escape.compact": "ESC",
    "modifier.vulnerability.name": "Vulnerability",
    "modifier.vulnerability.compact": "VULN",
    "modifier.potency.name": "Potency",
    "modifier.potency.compact": "POT",
    "modifier.traps.name": "Trap Avoidance",
    "modifier.traps.compact": "TRAP",
    "modifier.willpower.name": "Willpower",
    "modifier.willpower.compact": "WILL",
    "modifier.spread.name": "Spread",
    "modifier.spread.compact": "SPRD",

    "flag.blocksAttack.name": "Cannot Attack",
    "flag.blocksEscape.name": "Cannot Escape",
    "flag.blocksAssist.name": "Cannot Assist",
    "flag.blocksBonusEscape.name": "No Bonus Escapes",
    "flag.blocksMoving.name": "Cannot Move",
    "flag.skipsTraps.name": "Ignores Traps",
    "flag.skipsTurn.name": "Skips Turn",
    "flag.incapacitated.name": "Incapacitated",

    "failure.invalidActor.text": "Invalid character.",
    "failure.invalidMove.text": "Invalid move.",
    "failure.invalidBinding.text": "Invalid binding.",
    "failure.invalidTarget.text": "Invalid target.",
    "failure.duplicateTargets.text": "Each target can only be selected once.",

    "failure.wrongPhase.text": "This action cannot be used during this phase.",
    "failure.actorAlreadyActed.text": "This character has already acted.",
    "failure.actorSkipped.text": "This character's turn was skipped.",
    "failure.actorImmobilized.text": "This character cannot move.",
    "failure.actorIncapacitated.text": "This character is incapacitated.",
    "failure.targetIncapacitated.text": "This target is incapacitated.",

    "failure.moveUnavailable.text": "This move is unavailable.",
    "failure.attackUnavailable.text": "This character cannot attack.",
    "failure.assistUnavailable.text": "Cannot Assist",
    "failure.escapeUnavailable.text": "This character cannot escape.",
    "failure.bonusUnavailable.text": "Bonus Escape Blocked",
    "failure.bindingRestriction.text": "Bindings prevent this action.",
    "failure.cooldownIncomplete.text": "This move is still on cooldown.",
    "failure.insufficientResource.text": "Not enough resources.",
    "failure.insufficientTargets.text": "Not enough valid targets.",

};

