import { StringTable } from "../../src/ui/presentation/presentation";


export const systemStrings: StringTable = {
    "phase.player.name": "Player",
    "phase.enemy.name": "Enemy",

    "stance.standing.name": "Standing",
    "stance.moving.name": "Moving",

    "ui.action.ready": "Ready",
    "ui.action.acted": "Acted",
    "ui.action.skipped": "Skipped",
    "ui.action.unavailable": "Unavailable",
    "ui.battleOverview.endTurn": "End Turn",
    "ui.battleOverview.enemies": "Enemies",
    "ui.battleOverview.enemiesRemaining": "{count} remaining",
    "ui.battleOverview.gameLog": "Game Log",
    "ui.battleOverview.noEncounter": "Battle",
    "ui.battleOverview.party": "Party",
    "ui.battleOverview.partyCount": "{active} / {total}",
    "ui.battleOverview.phase": "{phase} Phase",
    "ui.battleOverview.round": "Round {round}",
    "ui.battleOverview.settings": "Settings",
    "ui.characterDetails.back": "Go Back",
    "ui.characterDetails.bindingValue": "{value}",
    "ui.characterDetails.bindingsHeading": "Bindings / {count} Zones",
    "ui.characterDetails.blocked": "Blk",
    "ui.characterDetails.changeStance": "Change Stance",
    "ui.characterDetails.commandsHeading": "Commands / {character}",
    "ui.characterDetails.cooldown": "Cooldown {count}",
    "ui.characterDetails.effectModifier": "{modifier} {value}",
    "ui.characterDetails.effectsHeading": "Effects",
    "ui.characterDetails.escape": "Escape",
    "ui.characterDetails.linkedEntity": "↗ {entity}",
    "ui.characterDetails.modifierValue": "{value}",
    "ui.characterDetails.rosterLabel": "Party roster",
    "ui.characterDetails.rounds": "{count} Rounds",
    "ui.characterDetails.selectMove": "Select Move",
    "ui.characterDetails.shortcut": "[{shortcut}]",
    "ui.characterDetails.statusHeading": "Status & Capabilities",
    "ui.characterDetails.statusValue": "{status} {value}",
    "ui.characterDetails.subtitle": "{character} / {difficulty} View",
    "ui.characterDetails.tagAlly": "Ally",
    "ui.characterDetails.tagAoe": "AOE",
    "ui.characterDetails.tagBuff": "Buff",
    "ui.characterDetails.tagDamage": "Damage",
    "ui.characterDetails.tagDebuff": "Debuff",
    "ui.characterDetails.tagEnemy": "Enemy",
    "ui.characterDetails.tagHits": "{count} Hits",
    "ui.characterDetails.tagSelf": "Self",
    "ui.effects.none": "No effects",
    "ui.effects.more": "+{count} more",
    "ui.intentions.more": "+{count}",
    "ui.intentions.moreAccessible": "{count} more intentions",
    "ui.partyCard.blockedCapabilities": "Blocked capabilities",
    "ui.partyCard.bindings": "Bindings",
    "ui.partyCard.effects": "Effects",
    "ui.targeting.actionEffects": "Action Effects",
    "ui.targeting.addMove": "Add {move}",
    "ui.targeting.allEnemies": "Target / All Enemies",
    "ui.targeting.allPlayers": "Target / All Players",
    "ui.targeting.allTargets": "Target / All Targets",
    "ui.targeting.automaticTarget": "Automatic Target",
    "ui.targeting.back": "Go Back",
    "ui.targeting.bindingAmount": "+{amount}",
    "ui.targeting.blockMove": "Block {move}",
    "ui.targeting.chance": "{band} · {chance}%",
    "ui.targeting.characterSummary": "{action} · {stance}",
    "ui.targeting.chooseMany": "Target / Choose {count}",
    "ui.targeting.chooseOne": "Target / Choose One",
    "ui.targeting.damageAmount": "{amount} damage",
    "ui.targeting.damageRange": "{min}–{max}",
    "ui.targeting.effectAccuracy": "Accuracy",
    "ui.targeting.effectBinding": "Binding",
    "ui.targeting.effectBuff": "Buff",
    "ui.targeting.effectDamage": "Damage",
    "ui.targeting.effectMove": "Move",
    "ui.targeting.effectTrap": "Trap",
    "ui.targeting.operationAdd": "Add",
    "ui.targeting.operationDefeat": "Defeat",
    "ui.targeting.operationRemove": "Remove",
    "ui.targeting.operationSpawn": "Spawn",
    "ui.targeting.predetermined": "Target / Automatic",
    "ui.targeting.trapAmount": "Amount {amount}",
    "ui.targeting.use": "Use {move}",
    "ui.targeting.value": "{current} / {max}",

    "moveType.arms.compact": "Arms",
    "moveType.mouth.compact": "Mouth",
    "moveType.legs.compact": "Legs",
    "moveType.none.compact": "None",

    "difficulty.casual.name": "Casual",
    "difficulty.casual.desc": "...",
    "difficulty.standard.name": "Standard",
    "difficulty.standard.desc": "...",
    "difficulty.veteran.name": "Veteran",
    "difficulty.veteran.desc": "...",
    "difficulty.extreme.name": "Extreme",
    "difficulty.extreme.desc": "...",
    "difficulty.mythic.name": "Mythic",
    "difficulty.mythic.desc": "...",

    "bindingLevel.none.name": "None",
    "bindingLevel.light.name": "Light",
    "bindingLevel.moderate.name": "Moderate",
    "bindingLevel.heavy.name": "Heavy",
    "bindingLevel.severe.name": "Severe",
    "bindingLevel.overwhelming.name": "Overwhelming",
    "bindingLevel.max.name": "Maximum",

    "hitBand.miss.name": "Miss",
    "hitBand.graze.name": "Graze",
    "hitBand.hit.name": "Hit",
    "hitBand.crit.name": "Crit",
    "hitBand.none.name": "None",

    "battleState.ongoing.name": "Ongoing",
    "battleState.victory.name": "Victory",
    "battleState.defeat.name": "Defeat",

    "status.bound.name": "Bound",
    "status.bound.desc": "...",
    "status.gagged.name": "Gagged",
    "status.gagged.desc": "...",
    "status.hobbled.name": "Hobbled",
    "status.hobbled.desc": "...",
    "status.vibrating.name": "Vibrating",
    "status.vibrating.desc": "...",
    "status.submissive.name": "Submissive",
    "status.submissive.desc": "...",
    "status.breathless.name": "Breathless",
    "status.breathless.desc": "...",
    "status.blinded.name": "Blinded",
    "status.blinded.desc": "...",
    "status.immobilized.name": "Immobilized",
    "status.immobilized.desc": "...",
    "status.helpless.name": "Helpless",
    "status.helpless.desc": "...",
    "status.stunned.name": "Stunned",
    "status.stunned.desc": "...",
    "status.incapacitated.name": "Incapacitated",
    "status.incapacitated.desc": "...",
    "status.servitude.name": "Servitude",
    "status.servitude.desc": "...",

    "modifier.hitarms.name": "Accuracy(Arms)",
    "modifier.hitmouth.name": "Accuracy(Mouth)",
    "modifier.hitlegs.name": "Accuracy(Legs)",
    "modifier.hit.name": "Accuracy",
    "modifier.defense.name": "Defense",
    "modifier.escape.name": "Escape",
    "modifier.vulnerability.name": "Vulnerability",
    "modifier.potency.name": "Potency",
    "modifier.traps.name": "Trap Avoidance",
    "modifier.willpower.name": "Willpower",
    "modifier.spread.name": "Spread",

    "flag.blocksAttack.name": "Cannot Attack",
    "flag.blocksEscape.name": "Cannot Escape",
    "flag.blocksAssist.name": "Cannot Assist",
    "flag.blocksBonusEscape.name": "No Bonus Escapes",
    "flag.blocksMoving.name": "Cannot Move",
    "flag.skipsTraps.name": "Ignores Traps",
    "flag.skipsTurn.name": "Skips Turn",
    "flag.incapacitated.name": "Incapacitated",

    "failure.invalidActor.text": "Invalid character.",
    "failure.invalidMove.text": "Invalid move.",
    "failure.invalidBinding.text": "Invalid binding.",
    "failure.invalidTarget.text": "Invalid target.",
    "failure.duplicateTargets.text": "Each target can only be selected once.",

    "failure.wrongPhase.text": "This action cannot be used during this phase.",
    "failure.actorAlreadyActed.text": "This character has already acted.",
    "failure.actorSkipped.text": "This character cannot act this turn.",
    "failure.actorImmobilized.text": "This character cannot move.",
    "failure.actorIncapacitated.text": "This character is incapacitated.",
    "failure.targetIncapacitated.text": "This target is incapacitated.",

    "failure.moveUnavailable.text": "This move is unavailable.",
    "failure.attackUnavailable.text": "This character cannot attack.",
    "failure.assistUnavailable.text": "This character cannot assist.",
    "failure.escapeUnavailable.text": "This character cannot escape.",
    "failure.bindingRestriction.text": "Bindings prevent this action.",
    "failure.cooldownIncomplete.text": "This move is still on cooldown.",
    "failure.insufficientResource.text": "Not enough resources.",
    "failure.insufficientTargets.text": "Not enough valid targets.",

};

