export const systemStrings = {
    "phase.player.name": "Player",
    "phase.enemy.name": "Enemy",

    "stance.standing.name": "Standing",
    "stance.moving.name": "Moving",

    "difficulty.casual.name": "Casual",
    "difficulty.casual.desc": "...",
    "difficulty.standard.name": "Standard",
    "difficulty.standard.desc": "...",
    "difficulty.veteran.name": "Veteran",
    "difficulty.veteran.desc": "...",
    "difficulty.extreme.name": "Extreme",
    "difficulty.extreme.desc": "...",
    "difficulty.mythic.name": "Mythic",
    "difficulty.mythic.desc": "...",

    "bindingLevel.none.name": "None",
    "bindingLevel.light.name": "Light",
    "bindingLevel.moderate.name": "Moderate",
    "bindingLevel.heavy.name": "Heavy",
    "bindingLevel.severe.name": "Severe",
    "bindingLevel.overwhelming.name": "Overwhelming",

    "hitBand.miss.name": "Miss",
    "hitBand.graze.name": "Graze",
    "hitBand.hit.name": "Hit",
    "hitBand.crit.name": "Critical",
    "hitBand.none.name": "None",

    "battleState.ongoing.name": "Ongoing",
    "battleState.victory.name": "Victory",
    "battleState.defeat.name": "Defeat",

    "status.bound.name": "Bound",
    "status.bound.desc": "...",
    "status.gagged.name": "Gagged",
    "status.gagged.desc": "...",
    "status.hobbled.name": "Hobbled",
    "status.hobbled.desc": "...",
    "status.vibrating.name": "Vibrating",
    "status.vibrating.desc": "...",
    "status.submissive.name": "Submissive",
    "status.submissive.desc": "...",
    "status.breathless.name": "Breathless",
    "status.breathless.desc": "...",
    "status.blinded.name": "Blinded",
    "status.blinded.desc": "...",
    "status.immobilized.name": "Immobilized",
    "status.immobilized.desc": "...",
    "status.helpless.name": "Helpless",
    "status.helpless.desc": "...",
    "status.stunned.name": "Stunned",
    "status.stunned.desc": "...",
    "status.incapacitated.name": "Incapacitated",
    "status.incapacitated.desc": "...",
    "status.servitude.name": "Servitude",
    "status.servitude.desc": "...",

    "modifier.hitarms.name": "Accuracy(Arms)",
    "modifier.hitmouth.name": "Accuracy(Mouth)",
    "modifier.hitlegs.name": "Accuracy(Legs)",
    "modifier.hit.name": "Accuracy",
    "modifier.defense.name": "Defense",
    "modifier.escape.name": "Escape",
    "modifier.vulnerability.name": "Vulnerability",
    "modifier.potency.name": "Potency",
    "modifier.traps.name": "Trap Avoidance",
    "modifier.willpower.name": "Willpower",
    "modifier.spread.name": "Spread",

    "flag.blocksAttack.name": "Cannot Attack",
    "flag.blocksEscape.name": "Cannot Escape",
    "flag.blocksAssist.name": "Cannot Assist",
    "flag.blocksBonusEscape.name": "No Bonus Escapes",
    "flag.blocksMoving.name": "Cannot Move",
    "flag.skipsTraps.name": "Ignores Traps",
    "flag.skipsTurn.name": "Skips Turn",
    "flag.incapacitated.name": "Incapacitated",

    "failure.invalidActor.text": "Invalid character.",
    "failure.invalidMove.text": "Invalid move.",
    "failure.invalidBinding.text": "Invalid binding.",
    "failure.invalidTarget.text": "Invalid target.",
    "failure.duplicateTargets.text": "Each target can only be selected once.",

    "failure.wrongPhase.text": "This action cannot be used during this phase.",
    "failure.actorAlreadyActed.text": "This character has already acted.",
    "failure.actorSkipped.text": "This character cannot act this turn.",
    "failure.actorImmobilized.text": "This character cannot move.",
    "failure.actorIncapacitated.text": "This character is incapacitated.",
    "failure.targetIncapacitated.text": "This target is incapacitated.",

    "failure.moveUnavailable.text": "This move is unavailable.",
    "failure.attackUnavailable.text": "This character cannot attack.",
    "failure.assistUnavailable.text": "This character cannot assist.",
    "failure.escapeUnavailable.text": "This character cannot escape.",
    "failure.bindingRestriction.text": "Bindings prevent this action.",
    "failure.cooldownIncomplete.text": "This move is still on cooldown.",
    "failure.insufficientResource.text": "Not enough resources.",
    "failure.insufficientTargets.text": "Not enough valid targets.",

};