import { ko } from "./content/characters/ko";
import { skunkette } from "./content/enemies/skunk/skunkette";
import { GameEngine } from "./engine/engine";

const engine = new GameEngine();
engine.loadCharacter(ko);
engine.loadEnemy(skunkette);
const actions = engine.getActions("ko");
console.log("~~Actions~~");
console.dir(actions);
console.log("~~State~~");
console.dir(engine.getGameState());
let events = engine.executeAction({type:"attack",actor:"ko","move":"telekinesis",targets:["skunkette1"]});
console.log("~~Events: Attack #1~~");
console.dir(events, {depth:null});
events = engine.executeAction({type:"attack",actor:"ko","move":"telekinesis",targets:["skunkette1"]});
console.log("~~Events: Attack #2~~");
console.dir(events, {depth:null});
events = engine.executeAction({type:"endTurn"});
console.log("~~End Turn #1~~");
console.dir(events, {depth:null});
events = engine.executeAction({type:"attack",actor:"ko","move":"telekinesis",targets:["skunkette1"]});
console.log("~~Events: Attack #3~~");
console.dir(events, {depth:null});
events = engine.executeAction({type:"endTurn"});
console.log("~~End Turn #2~~");
console.dir(events, {depth:null});
events = engine.executeAction({type:"attack",actor:"ko","move":"telekinesis",targets:["skunkette1"]});
console.log("~~Events: Attack #4~~");
console.dir(events, {depth:null});
console.log("~~State~~");
console.dir(engine.getGameState());
